vim.keymap.set('n', 'W', '<CMD>w<CR>', { desc = 'Write file' })

-- Telekasten keymaps
vim.keymap.set('n', '<leader>zf', ':lua require("telekasten").find_notes()<CR>', { desc = 'Find Notes' })
vim.keymap.set('n', '<leader>zd', ':lua require("telekasten").find_daily_notes()<CR>', { desc = 'Find Daily Notes' })
vim.keymap.set('n', '<leader>zg', ':lua require("telekasten").search_notes()<CR>', { desc = 'Search Notes' })
vim.keymap.set('n', '<leader>zz', ':lua require("telekasten").follow_link()<CR>', { desc = 'Follow Link' })
vim.keymap.set('n', '<leader>zT', ':lua require("telekasten").goto_today()<CR>', { desc = 'Go To Today' })
vim.keymap.set('n', '<leader>zW', ':lua require("telekasten").goto_thisweek()<CR>', { desc = 'Go To This Week' })
vim.keymap.set('n', '<leader>zw', ':lua require("telekasten").find_weekly_notes()<CR>', { desc = 'Find Weekly Notes' })
vim.keymap.set('n', '<leader>zn', ':lua require("telekasten").new_note()<CR>', { desc = 'New Note' })
vim.keymap.set('n', '<leader>zN', ':lua require("telekasten").new_templated_note()<CR>', { desc = 'New Templated Note' })
vim.keymap.set('n', '<leader>zy', ':lua require("telekasten").yank_notelink()<CR>', { desc = 'Yank Notelink' })
vim.keymap.set('n', '<leader>zc', ':lua require("telekasten").show_calendar()<CR>', { desc = 'Show Calendar' })
vim.keymap.set('n', '<leader>zC', ':CalendarT<CR>', { desc = ':CalendarT' })
vim.keymap.set('n', '<leader>zi', ':lua require("telekasten").paste_img_and_link()<CR>', { desc = 'Paste Img And Link' })
vim.keymap.set('n', '<leader>zt', ':lua require("telekasten").toggle_todo()<CR>', { desc = 'Toggle Todo' })
vim.keymap.set('v', '<leader>zt', ':lua require("telekasten").toggle_todo({ v = true })<CR>', { desc = 'Toggle Todo' })
vim.keymap.set('n', '<leader>zb', ':lua require("telekasten").show_backlinks()<CR>', { desc = 'Show Backlinks' })
vim.keymap.set('n', '<leader>zF', ':lua require("telekasten").find_friends()<CR>', { desc = 'Find Friends' })
vim.keymap.set('n', '<leader>zp', ':lua require("telekasten").preview_img()<CR>', { desc = 'Preview Image' })
vim.keymap.set('n', '<leader>zm', ':lua require("telekasten").browse_media()<CR>', { desc = 'Browse Media' })
vim.keymap.set('n', '<leader>#', ':lua require("telekasten").show_tags()<CR>', { desc = 'Show Tags' })
